### ISSUE TITLE
NEw issue with SEG mode

### ISSUE THREAD

**Issue by pogilon** [lzx1413/labelImg#4]
When I click settings and Seg mode the program kind of crashes and outputs the following:
"
AttributeError: 'NoneType' object has no attribute 'width'
Traceback (most recent call last):
  File "/labelImgPlus/libs/canvas.py", line 106, in mouseMoveEvent
    pos = self.transformPos(ev.posF())
  File "/labelImgPlus/libs/canvas.py", line 438, in transformPos
    return point / self.scale - self.offsetToCenter()
  File "/labelImgPlus/libs/canvas.py", line 443, in offsetToCenter
    w, h = self.pixmap.width() * s, self.pixmap.height() * s
"

**Comment by lzx1413** [comment]
there are still problems while switching task mode, I'll test it and fix the bug in a few days.
