### ISSUE TITLE
Can't save markup data

### ISSUE THREAD

**Issue by mrgloom** [lzx1413/labelImg#7]
I'm trying to run labelImgPlus under Windows using anaconda python 2.

But seems it can't save polygon markup data:

```
C:\Users\myuser\Anaconda2\python.exe labelImg.py

color map [u'0,0,0\n', u'255,0,0,128\n', u'0,255,0,128\n', u'0,0,255,128\n', u'1
39,0,139,128\n', u'0,139,139,128\n', u'137,104,205,128\n', u'104,34,139\n', u'22
4,102,255\n', u'255,187,255\n', u'238,58,140\n', u'205,41,144\n', u'0,191,255\n'
, u'139,125,123\n', u'240,255,240\n', u'205,179,139\n', u'34,139,34\n', u'127,25
5,0\n', u'0,100,0\n', u'240,255,240\n', u'255,246,143\n']
[<PyQt4.QtGui.QColor object at 0x000000000429BDD8>, <PyQt4.QtGui.QColor object a
t 0x00000000044BD278>, <PyQt4.QtGui.QColor object at 0x00000000044BD128>, <PyQt4
.QtGui.QColor object at 0x00000000044BD0B8>, <PyQt4.QtGui.QColor object at 0x000
00000044BD2E8>, <PyQt4.QtGui.QColor object at 0x00000000044BD358>, <PyQt4.QtGui.
QColor object at 0x00000000044BD3C8>, <PyQt4.QtGui.QColor object at 0x0000000004
4BD438>, <PyQt4.QtGui.QColor object at 0x00000000044BD4A8>, <PyQt4.QtGui.QColor
object at 0x00000000044BD518>, <PyQt4.QtGui.QColor object at 0x00000000044BD588>
, <PyQt4.QtGui.QColor object at 0x00000000044BD5F8>, <PyQt4.QtGui.QColor object
at 0x00000000044BD668>, <PyQt4.QtGui.QColor object at 0x00000000044BD6D8>, <PyQt
4.QtGui.QColor object at 0x00000000044BD748>, <PyQt4.QtGui.QColor object at 0x00
000000044BD7B8>, <PyQt4.QtGui.QColor object at 0x00000000044BD828>, <PyQt4.QtGui
.QColor object at 0x00000000044BD898>, <PyQt4.QtGui.QColor object at 0x000000000
44BD908>, <PyQt4.QtGui.QColor object at 0x00000000044BD978>, <PyQt4.QtGui.QColor
 object at 0x00000000044BD9E8>]
change mode to {'enable_color_map': False, 'mode': 1}
app mode 1
4
4
{u'01-hair': 0, u'None': 0, u'02-skin': 0, u'03-body': 0}
shapeSelectionChanged
shapeSelectionChanged
shapeSelectionChanged
shapeSelectionChanged
shape type POLYGON
Traceback (most recent call last):
  File "labelImg.py", line 1555, in saveFileAs
    self._saveFile(self.saveFileDialog())
  File "labelImg.py", line 1573, in _saveFile
    if filename and self.saveLabels(filename):
  File "labelImg.py", line 1030, in saveLabels
    with open(self.defaultSaveDir + 'label_num_dic.json', 'w') as label_num_file
:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by lzx1413** [comment]
The path of the images is better with only English words, this error indicated that the defaultSaveDir is not generated from the image directory.
